name: CI/CD Workflow

on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || (github.event_name == 'push' && github.ref_type == 'tag')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances JavaScript
        run:  npm install

      - name: Lint du fichier index.js
        run:  npm run lint-index

  test-addition:
    name: Test de addition.js
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || (github.event_name == 'push' && github.ref_type == 'tag')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances JavaScript
        run:  npm install

      - name: Test
        run: |
        if npm test; then
          echo "Test succeeded" # Le test a réussi
          echo "::set-output name=test-result::success" # Définir un statut personnalisé
        else
          echo "Test failed" # Le test a échoué
          echo "::set-output name=test-result::failure" # Définir un statut personnalisé
          exit 1 # Exit avec un code d'erreur pour indiquer que le test a échoué
        fi
      - name: Set GitHub status
        if: always() # Cette étape doit toujours s'exécuter, même en cas d'échec du test
        run: |
          if [ "${{ steps.test-addition.outputs.test-result }}" == "success" ]; then
            echo "Tests succeeded"
          else
            echo "Tests failed"
            exit 1 # Exit avec un code d'erreur pour indiquer que le test a échoué
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      
