name: CI/CD Workflow

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    name: Construction
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances JavaScript
        run: npm install

      - name: Build
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances JavaScript
        run: npm install

      - name: Lint du fichier addition.js
        run: npm run lint-addition

      - name: Lint du fichier Dockerfile
        uses: hadolint/hadolint-action@latest
        with:
          dockerfile: Dockerfile

  test-addition:
    name: Test de addition.js
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances JavaScript
        run: npm install

      - name: Test
        run: npm test

      - name: Definition du statut GitHub
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Le test a été réussi"
          else
            echo "Le test a échoué"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-test:
    name: Build and Run Dockerfile
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@latest

      - name: Installation Docker
        uses: docker/setup-buildx-action@latest

      - name: Build bastoss bastosstonsoss/b-m-ci-cd:latest
        run: docker build --rm -t bastosstonsoss/b-m-ci-cd:latest .

      - name: Run bastosstonsoss/b-m-ci-cd:latest
        run: docker run --name addition -p 3000:3000 -d bastosstonsoss/b-m-ci-cd:latest

  deploy-image-tag:
    name: Push bastosstonsoss/b-m-ci-cd:latest
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs:
      - lint
      - jest-test
      - docker-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@latest

      - name: Installation Docker
        uses: docker/setup-buildx-action@latest

      - name: Build bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker build --rm -t bastosstonsoss/b-m-ci-cd:${{github.ref_name}} .

      - name: Connexion Docker Hub
        uses: docker/login-action@latest
        with:
          username: bastosstonsoss
          password: JeSaisPasCommentFaireSansRevelerMonMdp

      - name: Tag bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker tag bastosstonsoss/b-m-ci-cd:${{github.ref_name}} bastosstonsoss/b-m-ci-cd${{github.ref_name}}

      - name: Push bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker push bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
