name: Merge Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

     - name: Set version 
        id: set_version
        run: |
          # Récupérer la dernière version du dernier tag (si elle existe)
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")

          # Extraire la version à partir du tag
          LAST_VERSION=$(echo "$LAST_TAG" | sed 's/v//'   
          # Diviser la version en parties
          IFS='.' read -ra VERSION_PARTS <<< "$LAST_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}    
          ((PATCH=PATCH+1))

          TAG_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "TAG_VERSION: $TAG_VERSION   
          echo "$TAG_VERSION" > version.txt
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV
          echo "MINOR=${MINOR}" >> $GITHUB_ENV
          echo "PATCH=${PATCH}" >> $GITHUB_ENV
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}

  deploiment-image:
    name: Push bastosstonsoss/b-m-ci-cd:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Installation Docker
        uses: docker/setup-buildx-action@v3

      - name: Build bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker build --rm -t bastosstonsoss/b-m-ci-cd:${{github.ref_name}} .

      - name: Connexion Docker Hub
        uses: docker/login-action@v3
        with:
          username: bastosstonsoss
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Tag bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker tag bastosstonsoss/b-m-ci-cd:${{github.ref_name}} bastosstonsoss/b-m-ci-cd${{github.ref_name}}

      - name: Push bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker push bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
