name: Merge Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: |
          # Récupérer la dernière version du fichier (si elle existe)
          LAST_VERSION=$(cat version.txt 2>/dev/null || echo "1.0.0")

          # Diviser la version en parties
          IFS='.' read -ra VERSION_PARTS <<< "$LAST_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"

          ((PATCH=PATCH+1))

          TAG_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "TAG_VERSION: $TAG_VERSION"

          echo "$TAG_VERSION" > version.txt
          echo "MAJOR=${MAJOR}" >> $GITHUB_ENV
          echo "MINOR=${MINOR}" >> $GITHUB_ENV
          echo "PATCH=${PATCH}" >> $GITHUB_ENV
          echo "TAG_VERSION=${TAG_VERSION}" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}

      - name: Configure Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Tag
        run: |
          MAJOR=${MAJOR}
          MINOR=${MINOR}
          PATCH=${PATCH}
          TAG_VERSION=${TAG_VERSION}

          git tag -a $TAG_VERSION -m "Auto-generated tag for version $TAG_VERSION"
          git push origin $TAG_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploiment-image:
    name: Push bastosstonsoss/b-m-ci-cd:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Installation Docker
        uses: docker/setup-buildx-action@v3

      - name: Build bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker build --rm -t bastosstonsoss/b-m-ci-cd:${{github.ref_name}} .

      - name: Connexion Docker Hub
        uses: docker/login-action@v3
        with:
          username: bastosstonsoss
          password: ${{ secrets.PASSWORD_DOCKERHUB }}

      - name: Tag bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker tag bastosstonsoss/b-m-ci-cd:${{github.ref_name}} bastosstonsoss/b-m-ci-cd${{github.ref_name}}

      - name: Push bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
        run: docker push bastosstonsoss/b-m-ci-cd:${{github.ref_name}}
